baseURL = "https://btctranscripts.com/"
languageCode = "en-us"

theme = "ace-documentation"
orderSectionsby = "title"
ignoreFiles = [ "README.md", "LICENSE.md" ]

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "₿itcoin Transcripts"
    languageName = "English"
    weight = 1
  [languages.es]
    title = "Transcripciones de ₿itcoin"
    languageName = "Español"
    weight = 2
  [languages.pt]
    title = "Transcrições de ₿itcoin"
    languageName = "Português"
    weight = 2

[outputs]
    home = [ "HTML", "JSON"]
    page = [ "HTML"]

[params]
    disableReadmoreNav = true
    menushortcutsnewtab = true
    custom_js = ["js/custom.js"]
    custom_css = ["scss/custom.scss"]
    images = ["images/btctranscripts.png"]
    description = "A treasure trove of ₿itcoin transcripts (mostly recorded by @kanzure)"
    
[markup]
  [markup.tableOfContents]
    startLevel = 1
  [markup.goldmark.renderer]
    unsafe = true

[[menu.shortcuts]]
    name = "<i class='fab fa-github'></i>"
    url = "https://github.com/bitcointranscripts/bitcointranscripts"
    weight = 1
