baseURL = "//btctranscripts.com/"
languageCode = "en-us"
title = "₿itcoin Transcripts"

theme = "ace-documentation"
orderSectionsby = "title"
ignoreFiles = [ "README.md", "LICENSE.md" ]

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "₿itcoin Transcripts"
    languageName = "English"
    weight = 1
  [languages.es]
    title = "Transcripciones de ₿itcoin"
    languageName = "Español"
    weight = 2
  [languages.fr]
    title = "Transcriptions ₿itcoin"
    languageName = "Française"
    weight = 2

[outputs]
    home = [ "HTML", "JSON"]
    page = [ "HTML"]

[params]
    disableReadmoreNav = true
    menushortcutsnewtab = true
    custom_js = ["js/custom.js"]
    custom_css = ["scss/custom.scss"]
    
[markup]
  [markup.tableOfContents]
    startLevel = 1

[[menu.shortcuts]]
    name = "<i class='fab fa-github'></i>"
    url = "https://github.com/bitcointranscripts/bitcointranscripts"
    weight = 1
